-- bchat Database Schema
-- PostgreSQL 15+

-- PG15+ revoked default CREATE on public schema for non-owner roles.
-- Ensure the current user can create objects. Safe no-op if already granted.
GRANT ALL ON SCHEMA public TO CURRENT_USER;

-- Users: core identity table
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    telegram_id     BIGINT UNIQUE NOT NULL,
    telegram_username TEXT,
    first_name      TEXT NOT NULL,
    last_name       TEXT,

    -- ed25519 identity public key (hex)
    identity_pubkey TEXT NOT NULL,

    -- BIP32 derived address for this user (from master xpub)
    wallet_address  TEXT,
    wallet_index    INTEGER,

    -- TOTP 2FA (encrypted secret)
    totp_secret     TEXT,
    totp_enabled    BOOLEAN DEFAULT FALSE,

    -- X25519 public key for E2EE messaging (hex)
    encryption_pubkey TEXT,

    -- Role & admin chain of trust
    role            TEXT NOT NULL DEFAULT 'user', -- creator, admin, user
    verified_by     UUID REFERENCES users(id),   -- which admin verified this user/admin
    admin_signature TEXT,                         -- creator/admin signs this user's pubkey to prove legitimacy
    is_verified     BOOLEAN DEFAULT FALSE,
    is_active       BOOLEAN DEFAULT TRUE,

    -- Phone number (future: secondary verification)
    phone_number    TEXT,
    phone_verified  BOOLEAN DEFAULT FALSE,

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Admin verification chain: who promoted whom, with cryptographic proof
CREATE TABLE IF NOT EXISTS admin_chain (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admin_id        UUID NOT NULL REFERENCES users(id),
    promoted_by     UUID NOT NULL REFERENCES users(id),

    -- The promoter signs the new admin's identity pubkey
    -- This creates an unforgeable chain: creator -> admin -> admin
    signature       TEXT NOT NULL,  -- ed25519 sig of (admin_id || admin_pubkey || role || timestamp)
    signed_payload  TEXT NOT NULL,  -- the exact payload that was signed (for verification)

    role_granted    TEXT NOT NULL DEFAULT 'admin',
    granted_at      TIMESTAMPTZ DEFAULT NOW(),
    revoked_at      TIMESTAMPTZ,
    is_active       BOOLEAN DEFAULT TRUE
);

-- Conversations: direct messages and groups
-- (must be created before support_tickets which references it)
CREATE TABLE IF NOT EXISTS conversations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type            TEXT NOT NULL DEFAULT 'direct', -- direct, group
    name            TEXT,  -- for groups

    -- Group encryption key (sealed per-member, not stored in plaintext)
    -- Null for direct conversations (use pairwise DH)
    group_key_version INTEGER DEFAULT 0,

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Conversation members
CREATE TABLE IF NOT EXISTS conversation_members (
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Sealed group key for this member (hex, encrypted with member's X25519 pubkey)
    encrypted_group_key TEXT,

    role            TEXT NOT NULL DEFAULT 'member', -- admin, member
    joined_at       TIMESTAMPTZ DEFAULT NOW(),

    PRIMARY KEY (conversation_id, user_id)
);

-- Support tickets: in-app only, users NEVER get support via Telegram DMs
CREATE TABLE IF NOT EXISTS support_tickets (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id),
    assigned_admin  UUID REFERENCES users(id),
    conversation_id UUID REFERENCES conversations(id),
    status          TEXT NOT NULL DEFAULT 'open', -- open, assigned, resolved, closed
    subject         TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Device bindings: each user can have multiple trusted devices
CREATE TABLE IF NOT EXISTS devices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id       TEXT UNIQUE NOT NULL,
    fingerprint     TEXT NOT NULL,
    name            TEXT,
    platform        TEXT NOT NULL, -- ios, android, web
    trusted         BOOLEAN DEFAULT FALSE,
    last_seen       TIMESTAMPTZ DEFAULT NOW(),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Invite codes: generated by admins/bot for onboarding
CREATE TABLE IF NOT EXISTS invites (
    code            TEXT PRIMARY KEY,
    created_by      UUID REFERENCES users(id),
    telegram_user_id BIGINT,
    used_by         UUID REFERENCES users(id),
    used_at         TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Challenge-response records: audit trail for identity verifications
CREATE TABLE IF NOT EXISTS challenges (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id),
    nonce           TEXT NOT NULL,
    purpose         TEXT NOT NULL DEFAULT 'identity_verify',
    status          TEXT NOT NULL DEFAULT 'pending', -- pending, verified, expired
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    verified_at     TIMESTAMPTZ
);

-- Messages: server stores only encrypted blobs
CREATE TABLE IF NOT EXISTS messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       UUID NOT NULL REFERENCES users(id),

    -- Encrypted content (server cannot read this)
    ciphertext      TEXT NOT NULL,
    nonce           TEXT NOT NULL,

    -- Message metadata (not encrypted — visible to server for delivery)
    content_type    TEXT NOT NULL DEFAULT 'text', -- text, image, file

    created_at      TIMESTAMPTZ DEFAULT NOW(),

    -- For ordering within conversation
    sequence_num    BIGSERIAL
);

-- Audit log: security events
CREATE TABLE IF NOT EXISTS audit_log (
    id              BIGSERIAL PRIMARY KEY,
    user_id         UUID REFERENCES users(id),
    event_type      TEXT NOT NULL,
    details         JSONB,
    ip_address      INET,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Device bans: ban the HARDWARE, not just the account.
-- A new Telegram account on the same phone still hits this ban.
CREATE TABLE IF NOT EXISTS device_bans (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fingerprint     TEXT NOT NULL,        -- device hardware fingerprint (SHA-256 of hardware signals)
    hardware_id     TEXT,                 -- Secure Enclave / StrongBox key hash (strongest signal)
    ip_hash         TEXT,                 -- hashed IP (privacy-preserving, for correlation)
    banned_user_id  UUID REFERENCES users(id), -- the account that caused the ban
    banned_by       UUID REFERENCES users(id), -- admin who issued the ban
    reason          TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    expires_at      TIMESTAMPTZ,          -- null = permanent
    is_active       BOOLEAN DEFAULT TRUE
);

-- Invite chain: tracks who invited whom for accountability.
-- If user X keeps inviting bad actors, X loses invite privileges.
CREATE TABLE IF NOT EXISTS invite_chain (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inviter_id      UUID NOT NULL REFERENCES users(id),
    invitee_id      UUID NOT NULL REFERENCES users(id),
    invite_code     TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Inviter reputation: tracks trust score for invite privileges
CREATE TABLE IF NOT EXISTS inviter_reputation (
    user_id         UUID PRIMARY KEY REFERENCES users(id),
    invites_sent    INTEGER DEFAULT 0,
    invites_banned  INTEGER DEFAULT 0,    -- how many of their invitees got banned
    trust_score     REAL DEFAULT 1.0,     -- 0.0 = untrusted, 1.0 = fully trusted
    can_invite      BOOLEAN DEFAULT TRUE, -- revoked if too many bad invites
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Registration signals: collected at signup for device-level identity.
-- Even if they make a new Telegram account, these signals persist.
CREATE TABLE IF NOT EXISTS registration_signals (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id),
    fingerprint     TEXT NOT NULL,
    hardware_id     TEXT,                 -- hardware-bound key (strongest)
    screen_res      TEXT,                 -- screen resolution
    timezone        TEXT,                 -- timezone offset
    language        TEXT,                 -- device language
    ip_hash         TEXT,                 -- hashed IP at registration
    canvas_hash     TEXT,                 -- canvas fingerprint (web)
    webgl_hash      TEXT,                 -- WebGL renderer hash (web)
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Telegram join events: persisted so server restarts don't lose pending registrations
CREATE TABLE IF NOT EXISTS telegram_join_events (
    telegram_user_id BIGINT PRIMARY KEY,
    username         TEXT,
    first_name       TEXT NOT NULL,
    invite_code      TEXT,
    joined_at        TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id, sequence_num);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user_id ON conversation_members(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_challenges_user_id ON challenges(user_id, status);
CREATE INDEX IF NOT EXISTS idx_admin_chain_admin_id ON admin_chain(admin_id, is_active);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id ON support_tickets(user_id, status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_admin ON support_tickets(assigned_admin, status);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_device_bans_fingerprint ON device_bans(fingerprint, is_active);
CREATE INDEX IF NOT EXISTS idx_device_bans_hardware ON device_bans(hardware_id, is_active);
CREATE INDEX IF NOT EXISTS idx_invite_chain_inviter ON invite_chain(inviter_id);
CREATE INDEX IF NOT EXISTS idx_invite_chain_invitee ON invite_chain(invitee_id);
CREATE INDEX IF NOT EXISTS idx_registration_signals_fingerprint ON registration_signals(fingerprint);
CREATE INDEX IF NOT EXISTS idx_registration_signals_hardware ON registration_signals(hardware_id);
CREATE INDEX IF NOT EXISTS idx_registration_signals_ip ON registration_signals(ip_hash);
