-- bchat Database Schema
-- PostgreSQL 15+

-- Users: core identity table
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    telegram_id     BIGINT UNIQUE NOT NULL,
    telegram_username TEXT,
    first_name      TEXT NOT NULL,
    last_name       TEXT,

    -- ed25519 identity public key (hex)
    identity_pubkey TEXT NOT NULL,

    -- BIP32 derived address for this user (from master xpub)
    wallet_address  TEXT,
    wallet_index    INTEGER,

    -- TOTP 2FA (encrypted secret)
    totp_secret     TEXT,
    totp_enabled    BOOLEAN DEFAULT FALSE,

    -- X25519 public key for E2EE messaging (hex)
    encryption_pubkey TEXT,

    -- Status
    is_verified     BOOLEAN DEFAULT FALSE,
    is_active       BOOLEAN DEFAULT TRUE,

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Device bindings: each user can have multiple trusted devices
CREATE TABLE IF NOT EXISTS devices (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id       TEXT UNIQUE NOT NULL,
    fingerprint     TEXT NOT NULL,
    name            TEXT,
    platform        TEXT NOT NULL, -- ios, android, web
    trusted         BOOLEAN DEFAULT FALSE,
    last_seen       TIMESTAMPTZ DEFAULT NOW(),
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Invite codes: generated by admins/bot for onboarding
CREATE TABLE IF NOT EXISTS invites (
    code            TEXT PRIMARY KEY,
    created_by      UUID REFERENCES users(id),
    telegram_user_id BIGINT,
    used_by         UUID REFERENCES users(id),
    used_at         TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Challenge-response records: audit trail for identity verifications
CREATE TABLE IF NOT EXISTS challenges (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id),
    nonce           TEXT NOT NULL,
    purpose         TEXT NOT NULL DEFAULT 'identity_verify',
    status          TEXT NOT NULL DEFAULT 'pending', -- pending, verified, expired
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    verified_at     TIMESTAMPTZ
);

-- Conversations: direct messages and groups
CREATE TABLE IF NOT EXISTS conversations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type            TEXT NOT NULL DEFAULT 'direct', -- direct, group
    name            TEXT,  -- for groups

    -- Group encryption key (sealed per-member, not stored in plaintext)
    -- Null for direct conversations (use pairwise DH)
    group_key_version INTEGER DEFAULT 0,

    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Conversation members
CREATE TABLE IF NOT EXISTS conversation_members (
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Sealed group key for this member (hex, encrypted with member's X25519 pubkey)
    encrypted_group_key TEXT,

    role            TEXT NOT NULL DEFAULT 'member', -- admin, member
    joined_at       TIMESTAMPTZ DEFAULT NOW(),

    PRIMARY KEY (conversation_id, user_id)
);

-- Messages: server stores only encrypted blobs
CREATE TABLE IF NOT EXISTS messages (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       UUID NOT NULL REFERENCES users(id),

    -- Encrypted content (server cannot read this)
    ciphertext      TEXT NOT NULL,
    nonce           TEXT NOT NULL,

    -- Message metadata (not encrypted — visible to server for delivery)
    content_type    TEXT NOT NULL DEFAULT 'text', -- text, image, file

    created_at      TIMESTAMPTZ DEFAULT NOW(),

    -- For ordering within conversation
    sequence_num    BIGSERIAL
);

-- Audit log: security events
CREATE TABLE IF NOT EXISTS audit_log (
    id              BIGSERIAL PRIMARY KEY,
    user_id         UUID REFERENCES users(id),
    event_type      TEXT NOT NULL,
    details         JSONB,
    ip_address      INET,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id, sequence_num);
CREATE INDEX IF NOT EXISTS idx_messages_sender_id ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_conversation_members_user_id ON conversation_members(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_challenges_user_id ON challenges(user_id, status);
